### ISSUE TITLE
I have problems with install of testrpc

### ISSUE THREAD

**Issue by tzaika** [pipermerriam/eth-testrpc#112]
* `py-geth` Version: -
* `go-ethereum` Version: -
* Python Version: 2.7.12
* OS: linux (ubuntu 16.0,4)

### What was wrong?

Please include information like:

* full output of the error you received

command:  sudo pip install eth-testrpc

The directory '/home/tzaika/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/tzaika/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting eth-testrpc
  Downloading eth-testrpc-1.3.3.tar.gz
Requirement already satisfied: Werkzeug>=0.11.10 in /usr/local/lib/python2.7/dist-packages (from eth-testrpc)
Requirement already satisfied: click>=6.6 in /usr/local/lib/python2.7/dist-packages (from eth-testrpc)
Collecting ethereum<2.0.0,>=1.6.1 (from eth-testrpc)
  Downloading ethereum-1.6.1.tar.gz (128kB)
    100% |████████████████████████████████| 133kB 1.2MB/s 
Collecting json-rpc>=1.10.3 (from eth-testrpc)
  Downloading json_rpc-1.10.8-py2.py3-none-any.whl (40kB)
    100% |████████████████████████████████| 40kB 6.4MB/s 
Collecting rlp>=0.4.7 (from eth-testrpc)
  Downloading rlp-0.6.0.tar.gz
Requirement already satisfied: repoze.lru in /usr/local/lib/python2.7/dist-packages (from ethereum<2.0.0,>=1.6.1->eth-testrpc)
Requirement already satisfied: PyYAML in /usr/local/lib/python2.7/dist-packages (from ethereum<2.0.0,>=1.6.1->eth-testrpc)
Requirement already satisfied: pbkdf2 in /usr/local/lib/python2.7/dist-packages (from ethereum<2.0.0,>=1.6.1->eth-testrpc)
Requirement already satisfied: bitcoin in /usr/local/lib/python2.7/dist-packages (from ethereum<2.0.0,>=1.6.1->eth-testrpc)
Requirement already satisfied: pycryptodome>=3.3.1 in /usr/local/lib/python2.7/dist-packages (from ethereum<2.0.0,>=1.6.1->eth-testrpc)
Collecting secp256k1 (from ethereum<2.0.0,>=1.6.1->eth-testrpc)
  Downloading secp256k1-0.13.2.tar.gz (156kB)
    100% |████████████████████████████████| 163kB 1.9MB/s 
Collecting scrypt (from ethereum<2.0.0,>=1.6.1->eth-testrpc)
  Downloading scrypt-0.8.6.tar.gz (52kB)
    100% |████████████████████████████████| 61kB 2.0MB/s 
Collecting pysha3>=1.0.1 (from ethereum<2.0.0,>=1.6.1->eth-testrpc)
  Downloading pysha3-1.0.2-cp27-cp27mu-manylinux1_i686.whl (56kB)
    100% |████████████████████████████████| 61kB 8.1MB/s 
Collecting pyethash (from ethereum<2.0.0,>=1.6.1->eth-testrpc)
  Downloading pyethash-0.1.27.tar.gz
Requirement already satisfied: cffi>=1.3.0 in /usr/local/lib/python2.7/dist-packages (from secp256k1->ethereum<2.0.0,>=1.6.1->eth-testrpc)
Requirement already satisfied: pycparser in /usr/local/lib/python2.7/dist-packages (from cffi>=1.3.0->secp256k1->ethereum<2.0.0,>=1.6.1->eth-testrpc)
Installing collected packages: secp256k1, scrypt, pysha3, rlp, pyethash, ethereum, json-rpc, eth-testrpc
  Running setup.py install for secp256k1 ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-imzweV/secp256k1/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-vToneS-record/install-record.txt --single-version-externally-managed --compile:
    0.29.1
    Using bundled libsecp256k1
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-i686-2.7
    creating build/lib.linux-i686-2.7/secp256k1
    copying secp256k1/__main__.py -> build/lib.linux-i686-2.7/secp256k1
    copying secp256k1/__init__.py -> build/lib.linux-i686-2.7/secp256k1
    running build_clib
    /tmp/pip-build-imzweV/secp256k1/libsecp256k1/autogen.sh: 3: /tmp/pip-build-imzweV/secp256k1/libsecp256k1/autogen.sh: autoreconf: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-imzweV/secp256k1/setup.py", line 295, in <module>
        "Topic :: Security :: Cryptography"
      File "/usr/local/lib/python2.7/dist-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python2.7/dist-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python2.7/distutils/command/install.py", line 601, in run
        self.run_command('build')
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
        self.run_command(cmd_name)
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-imzweV/secp256k1/setup.py", line 165, in run
        cwd=absolute("libsecp256k1"),
      File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/tmp/pip-build-imzweV/secp256k1/libsecp256k1/autogen.sh']' returned non-zero exit status 127
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-imzweV/secp256k1/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-vToneS-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-imzweV/secp256k1/

* what command you ran
install

I have already solved some similar problems with:
pip install --upgrade setuptools
apt install -y libmysqlclient-dev

and yet i am stuck

**Comment by lucrussell** [comment]
You might need `autoconf` and `dh-autoreconf` packages:

    sudo apt-get update
    sudo apt-get install autoconf
    sudo apt-get install dh-autoreconf

**Comment by tarekbadrshalaan** [comment]
sudo apt-get update
sudo apt-get install autoconf
sudo apt-get install dh-autoreconf
sudo apt-get install libssl-dev
pip install eth-testrpc
