### ISSUE TITLE
seems like it's downstream but...

### ISSUE THREAD

**Issue by euri10** [pipermerriam/eth-testrpc#56]
* `py-geth` Version: 1.2.0
* `go-ethereum` Version: 1.4.11
* Python Version: 3.5
* OS: linux

### What was wrong?
ok I'm trying to run my tests on a machine I used 6 months ago, so I might have messed up with deps, but this seems so weird to me that nobody got this error yet, it seems like it's downstream in ethereum/tester.py 
while I can definitely understand that the print should have parenthesis for python3, I don't know how to fix in my install,
that serpent.py file, where does it come from ?
other machine runs the same code fine

```
Traceback (most recent call last):
  File "/usr/local/bin/py.test", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/_pytest/config.py", line 47, in main
    config = _prepareconfig(args, plugins)
  File "/usr/local/lib/python3.5/dist-packages/_pytest/config.py", line 132, in _prepareconfig
    pluginmanager=pluginmanager, args=args)
  File "/usr/local/lib/python3.5/dist-packages/_pytest/vendored_packages/pluggy.py", line 724, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/_pytest/vendored_packages/pluggy.py", line 338, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/_pytest/vendored_packages/pluggy.py", line 333, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "/usr/local/lib/python3.5/dist-packages/_pytest/vendored_packages/pluggy.py", line 595, in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
  File "/usr/local/lib/python3.5/dist-packages/_pytest/vendored_packages/pluggy.py", line 249, in _wrapped_call
    wrap_controller.send(call_outcome)
  File "/usr/local/lib/python3.5/dist-packages/_pytest/helpconfig.py", line 32, in pytest_cmdline_parse
    config = outcome.get_result()
  File "/usr/local/lib/python3.5/dist-packages/_pytest/vendored_packages/pluggy.py", line 278, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/local/lib/python3.5/dist-packages/_pytest/vendored_packages/pluggy.py", line 264, in __init__
    self.result = func()
  File "/usr/local/lib/python3.5/dist-packages/_pytest/vendored_packages/pluggy.py", line 596, in execute
    res = hook_impl.function(*args)
  File "/usr/local/lib/python3.5/dist-packages/_pytest/config.py", line 880, in pytest_cmdline_parse
    self.parse(args)
  File "/usr/local/lib/python3.5/dist-packages/_pytest/config.py", line 1030, in parse
    self._preparse(args, addopts=addopts)
  File "/usr/local/lib/python3.5/dist-packages/_pytest/config.py", line 993, in _preparse
    self.pluginmanager.load_setuptools_entrypoints(entrypoint_name)
  File "/usr/local/lib/python3.5/dist-packages/_pytest/vendored_packages/pluggy.py", line 501, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2230, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2236, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.5/dist-packages/populus-1.0.0b9-py3.5.egg/populus/__init__.py", line 3, in <module>
    from .project import Project
  File "/usr/local/lib/python3.5/dist-packages/populus-1.0.0b9-py3.5.egg/populus/project.py", line 39, in <module>
    from populus.chain import (
  File "/usr/local/lib/python3.5/dist-packages/populus-1.0.0b9-py3.5.egg/populus/chain.py", line 8, in <module>
    from testrpc import testrpc
  File "/usr/local/lib/python3.5/dist-packages/testrpc/testrpc.py", line 7, in <module>
    from ethereum.tester import (
  File "/usr/local/lib/python3.5/dist-packages/ethereum/tester.py", line 47, in <module>
    import serpent  # pylint: disable=wrong-import-position
  File "/usr/local/bin/serpent.py", line 225
    print json.dumps(o)
             ^
SyntaxError: invalid syntax
```
#### Cute Animal Picture

![omg it is cutet](http://www.photomonde.fr/wp-content/uploads/2013/01/Ornithorynque.jpg)

**Comment by euri10** [comment]
mmmm sorry, fixed by removing ethereum-serpent, dunno what it is nor how it got installled on that old machine, deps change so quickly that if you don't maintain a clean install regularly it can be a nightmare ;)
```
sudo pip3 uninstall ethereum-serpent
Uninstalling ethereum-serpent-2.0.2:
  /usr/local/lib/python3.5/dist-packages/__pycache__/pyserpent.cpython-35.pyc
  /usr/local/lib/python3.5/dist-packages/ethereum_serpent-2.0.2.dist-info/DESCRIPTION.rst
  /usr/local/lib/python3.5/dist-packages/ethereum_serpent-2.0.2.dist-info/INSTALLER
  /usr/local/lib/python3.5/dist-packages/ethereum_serpent-2.0.2.dist-info/METADATA
  /usr/local/lib/python3.5/dist-packages/ethereum_serpent-2.0.2.dist-info/RECORD
  /usr/local/lib/python3.5/dist-packages/ethereum_serpent-2.0.2.dist-info/WHEEL
  /usr/local/lib/python3.5/dist-packages/ethereum_serpent-2.0.2.dist-info/entry_points.txt
  /usr/local/lib/python3.5/dist-packages/ethereum_serpent-2.0.2.dist-info/metadata.json
  /usr/local/lib/python3.5/dist-packages/ethereum_serpent-2.0.2.dist-info/top_level.txt
  /usr/local/lib/python3.5/dist-packages/pyserpent.py
  /usr/local/lib/python3.5/dist-packages/serpent.py
  /usr/local/lib/python3.5/dist-packages/serpent_pyext.cpython-35m-x86_64-linux-gnu.so
Proceed (y/n)? y
  Successfully uninstalled ethereum-serpent-2.0.2
```
